#!/bin/bash

#########################################################
# 
# Platform: NCI Gadi HPC
# Description: index dup-marked and sorted BAM files parallel by sample
# Usage: first, run 'bash index_make_input.sh <cohort_name>', 
# then execute this script with 'qsub index_run_parallel.pbs'
# Details:
# 	Running index as a separate job re high charge rate for 
#	dedup/sort job. Expected run time at 24 CPU  ~ 3 mins 
#	for 30X and ~ 6.5 mins for 60X so it's fair to run this job 
#	as one (instead of splitting by normal vs tumour) or on 
#	express queue if queue times are long
#
# Author: Cali Willet
# cali.willet@sydney.edu.au
# Date last modified: 24/07/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance 
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational 
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
# 
######################################################### 
 
#PBS -P <project>
#PBS -N index
#PBS -l walltime=00:20:00
#PBS -l ncpus=1056
#PBS -l mem=2090GB
#PBS -q express
#PBS -W umask=022
#PBS -l wd
#PBS -o ./Logs/index.o 
#PBS -e ./Logs/index.e 
#PBS -lstorage=scratch/<project>
 
module load openmpi/4.0.2
module load nci-parallel/1.0.0

set -e

SCRIPT=./index.sh 

INPUTS=./Inputs/index.input 


NCPUS=24
sed -i "s/$/,$NCPUS/" $INPUTS 


#########################################################
# Do not edit below this line (unless running on a node that 
# does not have 48 CPU, in which case edit the value of 'CPN'
#########################################################

CPN=48 #CPUs per node 
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
