#!/bin/bash

#########################################################
# 
# Platform: NCI Gadi HPC
# Description: reformat split and disc files over parallel tasks
# Usage: first, run 'bash reformat_split_disc_make_input.sh <cohort_name>', 
# then execute this script with 'qsub reformat_split_disc_run_parallel.pbs'
# Details:
#       SAMblaster optionally outputs split reads and discordant reads 
#	to SAM format. These are useful for downstream SV detection and
# 	analysis. This set of scripts reformts the SAM to sorted and 
#	index BAM. After this script has been run successfully, the 
#	SAM files can be deleted. At 12 CPU per sample, 60X completes in
#	around 30 minutes.   
#
# Author: Cali Willet
# cali.willet@sydney.edu.au
# Date last modified: 31/07/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance 
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational 
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
# 
#########################################################


#PBS -P <project>
#PBS -N ref-SD
#PBS -l walltime=01:00:00
#PBS -l ncpus=288
#PBS -l mem=1140GB
#PBS -q normal
#PBS -W umask=022
#PBS -l wd
#PBS -o ./Logs/reformat_split_disc.o
#PBS -e ./Logs/reformat_split_disc.e
#PBS -lstorage=scratch/<project>

	
module load openmpi/4.0.2
module load nci-parallel/1.0.0

set -e

SCRIPT=./reformat_split_disc.sh  
INPUTS=./Inputs/reformat_split_disc.inputs  

NCPUS=12 # CPUs per parallel task
sed -i "s/$/,$NCPUS/" $INPUTS 

	
#########################################################
# Do not edit below this line  
#########################################################

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi 
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file

