#!/bin/bash

#########################################################
# 
# Platform: NCI Gadi HPC
# Description: split input fast pairs with fastp into 500,000 reads 
# per pair to enable massively parallel alignment and processing
# Usage: first, run 'bash split_fastq_make_input.sh <cohort_name>', 
# then execute this script with 'qsub spli_fastq_run_parallel.pbs'
# Details:
# 	Run 12 x 4 CPU splitting tasks per node. 4 CPU has optimal 
#	efficiency on Gadi normal nodes. If yo are in a rush, 8 CPU
#	works well too, but allow 8 CPU per task and give 7 CPU 
#	threads to fastp. Request whole nodes only - eg for 31 pairs, 
#	this requires 124 CPU to run all tasks in parallel, so 2.5 
# 	nodes --> round up to 3 nodes (144 CPU). A ~40 GB fastq will 
#	take ~ 40 mins to split.
# Author: Cali Willet
# cali.willet@sydney.edu.au
# Date last modified: 26/08/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance 
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational 
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
# 
#########################################################


#PBS -P <project>
#PBS -N split_fastq
#PBS -l walltime=1:00:00
#PBS -l ncpus=144
#PBS -l mem=570GB
#PBS -q normal
#PBS -W umask=022
#PBS -l wd
#PBS -o ./Logs/split_fastq.o
#PBS -e ./Logs/split_fastq.e
#PBS -lstorage=scratch/<project>

module load openmpi/4.0.2
module load nci-parallel/1.0.0

SCRIPT=./split_fastq.sh
INPUTS=./Inputs/split_fastq.inputs   

NCPUS=4 #cpus per parallel task. This can be increased, but 4 is optimal E 

mkdir -p ./Fastq_split ./Logs/Fastp



#########################################################
# Do not edit below this line (unless running on a node that 
# does not have 48 CPU, in which case edit the value of 'CPN'
#########################################################

CPN=48 #CPUs per node 
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file

